### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by angiecortez** [angelicanoriega/lim20181-Track-FE-markdown-list#16]
Hola Maria Angelica, mi feedback para ti es el siguiente:
### cli.js:
_El feedback que te podria dar es que tu linea de comandos la crees en una carpeta_ **cli.js**. Por otra parte podrías quitar tantos **console.log**, los retornos no pueden ser **console.log**; tambien, verifico que que en tu archivo **withoption.js**, verifico que hay dos objetos ****

**Comment by angelicanoriega** [comment]
gracias por el feedback, porque el nombre de la carpeta deberia ser cli.js ?
